### ISSUE TITLE
Possible to monitor an open/listening port?

### ISSUE THREAD

**Issue by StuartHaire** [IamTheFij/minitor-go#2]
Is there a way to monitor an open port that doesn't host a website, eg curl can't be used here? But could we use telnet or something else to monitor a port of a service is up and listening?

**Comment by IamTheFij** [comment]
Absolutely! There is nothing really curl specific to Minitor. It can execute any command that you want, so you can use telnet, netcat, or anything really.

The default Docker image doesn’t come with a whole lot to keep it small, but you can extend it and install any other commands and then execute those.
